projects:
  sls-appsync-api:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: tcvcoqxthrgl7a6oy7ksle3c6a
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://5wf6unnvija4nlknimdsqhmxsi.appsync-api.us-east-1.amazonaws.com/graphql
